export default [
  {
    Id: 0,
    Name: 'Buying Format',
    Items: [
      {Id: 0, Name: 'Auction'},
      {Id: 1, Name: 'Direct Sale'},
    ],
    Type: 'multiSelector',
  },
  {
    Id: 1,
    Name: 'Condition',
    Items: [
      {Id: 0, Name: 'New'},
      {Id: 1, Name: 'Used'},
    ],
    Type: 'multiSelector',
  },
  {
    Id: 2,
    Name: 'Category',
    Items: [
      {Id: 0, Name: 'Food'},
      {Id: 1, Name: 'Games'},
      {Id: 2, Name: 'Clothes'},
      {Id: 3, Name: 'Makeup'},
    ],
    Type: 'checkbox',
  },
  {Id: 3, Name: 'Price', Items: [], Type: 'doubleSlider', Max: 5000},
  {Id: 4, Name: 'Quantity', Items: [], Type: 'doubleSlider', Max: 100},
  {Id: 5, Name: 'Seller rate', Items: [], Type: 'slider', Max: 10},
  {
    Id: 6,
    Name: 'Brand',
    Items: [
      {Id: 0, Name: 'Acer', Qty: 18},
      {Id: 1, Name: 'Alcatel', Qty: 5},
      {Id: 2, Name: 'Apple', Qty: 62},
      {Id: 3, Name: 'BlackBerry', Qty: 8},
      {Id: 4, Name: 'Google', Qty: 12},
      {Id: 5, Name: 'Huawei', Qty: 4},
      {Id: 6, Name: 'Nokia', Qty: 2},
      {Id: 7, Name: 'Realme', Qty: 26},
    ],
    Type: 'checkbox',
  },
  {
    Id: 7,
    Name: 'Material',
    Items: [
      {Id: 0, Name: 'Leather', Qty: 60},
      {Id: 1, Name: 'Wood', Qty: 19},
      {Id: 2, Name: 'Fabric', Qty: 31},
      {Id: 3, Name: 'Polyester', Qty: 31},
    ],
    Type: 'checkbox',
  },
  {
    Id: 8,
    Name: 'Size',
    Items: [
      {Id: 0, Name: '41'},
      {Id: 1, Name: '42'},
      {Id: 2, Name: '44'},
      {Id: 3, Name: 'XS'},
      {Id: 4, Name: 'M'},
      {Id: 5, Name: 'XXL'},
    ],
    Type: 'multiSelector',
  },
  {Id: 9, Name: 'Products with warranty', Items: [], Type: 'switch'},
  {Id: 10, Name: 'Posts with discounts', Items: [], Type: 'switch'},
];
